export type Era = '史前' | '夏商周' | '秦汉' | '三国两晋南北朝' | '隋唐五代' | '宋辽金夏元' | '明清' | '近现代';

export type TimelineEvent = {
  id: string;
  era: Era;
  period: string;
  gregorianDate: string;
  title: string;
  summary: string;
  region: string;
  evidence: string;
};

export type ArchaeologySite = {
  id: string;
  name: string;
  region: string;
  period: string;
  latitude: number;
  longitude: number;
  highlight: string;
  significance: string;
  importance: '普通' | '重要' | '核心';
  culturalCircle?: string;
  relatedArtifacts?: string[];
  relatedEvents?: string[];
  description?: string;
};

export type CulturalCircle = {
  id: string;
  name: string;
  color: string;
  region: string;
  center: [number, number];
  radius: number;
  sites: string[];
};

export type SiteConnection = {
  from: string;
  to: string;
  type: '文化圈' | '时期';
  weight?: number;
  color?: string;
};

export type Artifact = {
  id: string;
  name: string;
  period: string;
  category: '陶器' | '玉器' | '青铜器' | '骨器' | '礼器';
  material: string;
  site: string;
  detail: string;
};

export type Debate = {
  id: string;
  title: string;
  topic: '年代学' | '社会形态' | '文化传播' | '技术起源';
  mainstream: string;
  alternative: string;
  evidenceLevel: '高' | '中' | '探索中';
};

export type Theme = {
  id: string;
  title: string;
  era: Era | '早期文明';
  region: string;
  summary: string;
  focus: string;
};

export const siteRoutes = [
  { href: '/', label: '首页', description: '总览与快速入口' },
  { href: '/timeline', label: '时间轴', description: '按时代浏览关键节点' },
  { href: '/archaeology-map', label: '考古地图', description: '按地域探索遗址分布' },
  { href: '/themes', label: '文明专题', description: '围绕典型文化做深度阅读' },
  { href: '/origins', label: '文化起源', description: '聚焦人类文化形成路径' },
  { href: '/artifacts', label: '文物库', description: '查看典型器物与证据' },
  { href: '/debates', label: '研究与争鸣', description: '比较不同学术观点' },
  { href: '/docs/implementation-plan', label: '实施计划', description: '阶段任务与交付节奏' },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: 'evt-1',
    era: '史前',
    period: '三皇五帝 (原始社会)',
    gregorianDate: '约前3000年 - 前2070年',
    title: '史前文明',
    summary: '包含更早的史前文明（前32-前31世纪），三皇（伏羲、燧人/女娲、神农）与五帝（黄帝、颛顼、帝喾、唐尧、虞舜）时期。',
    region: '黄河及长江流域',
    evidence: '仰韶文化、良渚文化等新石器时代遗址',
  },
  {
    id: 'evt-2',
    era: '夏商周',
    period: '夏朝',
    gregorianDate: '前2070年 - 前1600年',
    title: '夏朝建立 (奴隶社会)',
    summary: '中国历史上第一个奴隶制王朝，标志着“家天下”的开端。',
    region: '中原（今河南中西部、山西南部）',
    evidence: '二里头遗址及早期青铜器',
  },
  {
    id: 'evt-3',
    era: '夏商周',
    period: '商朝',
    gregorianDate: '前1600年 - 前1046年',
    title: '商朝与甲骨文',
    summary: '前1300年盘庚迁殷。青铜铸造、甲骨文字进入高度发展阶段，具有成熟的国家机器和礼制。',
    region: '黄河中下游',
    evidence: '殷墟遗址、甲骨文、司母戊鼎等',
  },
  {
    id: 'evt-4',
    era: '夏商周',
    period: '西周',
    gregorianDate: '前1046年 - 前771年',
    title: '西周分封与宗法',
    summary: '实行分封制与宗法制，确立了周天子的共主地位。',
    region: '关中与中原',
    evidence: '毛公鼎、何尊等带有长篇铭文的青铜器',
  },
  {
    id: 'evt-5',
    era: '夏商周',
    period: '春秋 (东周)',
    gregorianDate: '前770年 - 前476年',
    title: '春秋时期',
    summary: '周平王东迁洛邑，周王室衰微，诸侯争霸（春秋五霸）。',
    region: '黄河、长江流域',
    evidence: '侯马盟书、兵器及车马坑',
  },
  {
    id: 'evt-6',
    era: '夏商周',
    period: '战国 (东周)',
    gregorianDate: '前475年 - 前221年',
    title: '战国时期 (封建社会开端)',
    summary: '战国七雄并立，各国变法图强，思想文化空前繁荣（诸子百家），进入封建社会。',
    region: '黄河、长江流域',
    evidence: '曾侯乙编钟、兵马俑早期雏形',
  },
  {
    id: 'evt-7',
    era: '秦汉',
    period: '秦朝',
    gregorianDate: '前221年 - 前207年',
    title: '秦朝统一中国',
    summary: '中国历史上第一个大一统的封建帝国，统一度量衡、文字和货币，建立郡县制。',
    region: '全国',
    evidence: '秦始皇陵兵马俑、里耶秦简',
  },
  {
    id: 'evt-8',
    era: '秦汉',
    period: '西汉',
    gregorianDate: '前202年 - 8年',
    title: '西汉',
    summary: '汉高祖刘邦建立，汉武帝时期罢黜百家、独尊儒术，张骞出使西域开辟丝绸之路。',
    region: '全国',
    evidence: '马王堆汉墓、海昏侯墓',
  },
  {
    id: 'evt-9',
    era: '秦汉',
    period: '新朝',
    gregorianDate: '9年 - 23年',
    title: '王莽代汉与新朝',
    summary: '王莽篡汉建立新朝，推行托古改制，最终在绿林赤眉起义中覆灭。',
    region: '全国',
    evidence: '新莽铜嘉量',
  },
  {
    id: 'evt-10',
    era: '秦汉',
    period: '东汉',
    gregorianDate: '25年 - 220年',
    title: '东汉',
    summary: '光武帝刘秀建立东汉，恢复汉朝统治。',
    region: '全国',
    evidence: '击鼓说唱陶俑、熹平石经',
  },
  {
    id: 'evt-11-1',
    era: '三国两晋南北朝',
    period: '曹魏',
    gregorianDate: '220年 - 266年',
    title: '曹魏',
    summary: '曹丕代汉称帝，定都洛阳，实行九品中正制。',
    region: '北方',
    evidence: '曹魏邺城遗址',
  },
  {
    id: 'evt-11-2',
    era: '三国两晋南北朝',
    period: '蜀汉',
    gregorianDate: '221年 - 263年',
    title: '蜀汉',
    summary: '刘备在成都称帝，延续汉室法统。',
    region: '西南',
    evidence: '武侯祠遗迹',
  },
  {
    id: 'evt-11-3',
    era: '三国两晋南北朝',
    period: '孙吴',
    gregorianDate: '229年 - 280年',
    title: '孙吴',
    summary: '孙权在建业称帝，开发江南地区。',
    region: '江南',
    evidence: '走马楼吴简',
  },
  {
    id: 'evt-12',
    era: '三国两晋南北朝',
    period: '西晋',
    gregorianDate: '265年 - 316年',
    title: '西晋短暂统一',
    summary: '司马炎代魏建晋，后灭吴短暂统一全国。后因八王之乱及五胡内迁灭亡。',
    region: '全国',
    evidence: '晋代青瓷、家族墓地',
  },
  {
    id: 'evt-13-1',
    era: '三国两晋南北朝',
    period: '东晋',
    gregorianDate: '317年 - 420年',
    title: '东晋偏安',
    summary: '晋室南渡，衣冠南渡促进了江南地区的开发。',
    region: '南方',
    evidence: '王羲之书法（摹本）、东晋青瓷',
  },
  {
    id: 'evt-13-2',
    era: '三国两晋南北朝',
    period: '十六国',
    gregorianDate: '304年 - 439年',
    title: '五胡十六国',
    summary: '北方少数民族纷纷建立政权，经历了长期的割据混战。',
    region: '北方',
    evidence: '十六国时期佛像',
  },
  {
    id: 'evt-14-1',
    era: '三国两晋南北朝',
    period: '南朝 (宋齐梁陈)',
    gregorianDate: '420年 - 589年',
    title: '南朝更迭',
    summary: '南方先后经历刘宋、南齐、南梁、南陈四个朝代的更迭。',
    region: '南方',
    evidence: '南朝陵墓石刻',
  },
  {
    id: 'evt-14-2',
    era: '三国两晋南北朝',
    period: '北魏',
    gregorianDate: '386年 - 534年',
    title: '北魏统一北方',
    summary: '拓跋部建立北魏，孝文帝改革促进了深度的民族融合。',
    region: '北方',
    evidence: '云冈石窟、龙门石窟、北魏洛阳城遗址',
  },
  {
    id: 'evt-14-3',
    era: '三国两晋南北朝',
    period: '东魏与西魏',
    gregorianDate: '534年 - 557年',
    title: '北魏分裂',
    summary: '北魏分裂为东魏与西魏，各自发展。',
    region: '北方',
    evidence: '北朝石刻与造像',
  },
  {
    id: 'evt-14-4',
    era: '三国两晋南北朝',
    period: '北齐与北周',
    gregorianDate: '550年 - 581年',
    title: '北齐与北周对峙',
    summary: '高氏代东魏建北齐，宇文氏代西魏建北周，最终北周灭北齐统一北方。',
    region: '北方',
    evidence: '北齐壁画墓',
  },
  {
    id: 'evt-15',
    era: '隋唐五代',
    period: '隋朝',
    gregorianDate: '581年 - 618年',
    title: '隋朝大一统与大运河',
    summary: '结束南北朝分裂局面，开凿京杭大运河，创立科举制。',
    region: '全国',
    evidence: '隋大兴城（长安）遗址、大运河遗迹',
  },
  {
    id: 'evt-16',
    era: '隋唐五代',
    period: '唐朝',
    gregorianDate: '618年 - 907年',
    title: '大唐盛世',
    summary: '出现贞观之治、开元盛世，文化繁荣，对外交流频繁。',
    region: '全国',
    evidence: '唐长安城遗址、法门寺地宫、敦煌莫高窟盛唐壁画',
  },
  {
    id: 'evt-16-1',
    era: '隋唐五代',
    period: '武周',
    gregorianDate: '690年 - 705年',
    title: '武则天称帝',
    summary: '武则天废唐睿宗自立，改国号为周，是中国历史上唯一的女皇帝。',
    region: '全国',
    evidence: '乾陵无字碑、洛阳龙门石窟',
  },
  {
    id: 'evt-17-1',
    era: '隋唐五代',
    period: '五代 (梁唐晋汉周)',
    gregorianDate: '907年 - 960年',
    title: '五代更迭',
    summary: '中原地区先后经历后梁、后唐、后晋、后汉、后周五个短暂政权。',
    region: '北方',
    evidence: '五代石窟与壁画',
  },
  {
    id: 'evt-17-2',
    era: '隋唐五代',
    period: '十国',
    gregorianDate: '902年 - 979年',
    title: '十国割据',
    summary: '南方及部分北方地区先后存在十个割据政权。',
    region: '南方及部分北方',
    evidence: '王建墓、南唐二陵',
  },
  {
    id: 'evt-18-1',
    era: '宋辽金夏元',
    period: '辽朝',
    gregorianDate: '907年 - 1125年',
    title: '契丹建辽',
    summary: '耶律阿保机建立契丹国（后改国号为辽），与北宋形成长期对峙。',
    region: '北方',
    evidence: '辽代陈国公主墓',
  },
  {
    id: 'evt-18-2',
    era: '宋辽金夏元',
    period: '北宋',
    gregorianDate: '960年 - 1127年',
    title: '北宋建立与繁荣',
    summary: '赵匡胤陈桥兵变建立北宋，重文轻武，商品经济与城市文化高度繁荣。',
    region: '中原及南方',
    evidence: '清明上河图、汝窑瓷器',
  },
  {
    id: 'evt-18-3',
    era: '宋辽金夏元',
    period: '西夏',
    gregorianDate: '1038年 - 1227年',
    title: '党项建夏',
    summary: '李元昊建立西夏，与宋、辽（金）鼎立，创制西夏文。',
    region: '西北',
    evidence: '西夏王陵、黑水城遗址',
  },
  {
    id: 'evt-18-4',
    era: '宋辽金夏元',
    period: '金朝',
    gregorianDate: '1115年 - 1234年',
    title: '女真建金',
    summary: '完颜阿骨打建立金朝，灭辽与北宋，与南宋划淮水为界对峙。',
    region: '北方',
    evidence: '金中都水关遗址',
  },
  {
    id: 'evt-19',
    era: '宋辽金夏元',
    period: '南宋',
    gregorianDate: '1127年 - 1279年',
    title: '靖康之变与南宋偏安',
    summary: '金灭北宋后，宋室南迁建立南宋，经济重心彻底南移。',
    region: '南方',
    evidence: '南海一号沉船、南宋官窑',
  },
  {
    id: 'evt-19-1',
    era: '宋辽金夏元',
    period: '蒙古',
    gregorianDate: '1206年 - 1271年',
    title: '成吉思汗建立蒙古汗国',
    summary: '铁木真统一蒙古各部，被尊为成吉思汗，建立大蒙古国。1271年忽必烈改国号为元。',
    region: '蒙古高原',
    evidence: '成吉思汗陵',
  },
  {
    id: 'evt-20',
    era: '宋辽金夏元',
    period: '元朝',
    gregorianDate: '1271年 - 1368年',
    title: '蒙元帝国建立',
    summary: '忽必烈建立元朝，统一全国，疆域空前辽阔，设立行省制度。',
    region: '全国',
    evidence: '元大都遗址、青花瓷',
  },
  {
    id: 'evt-21',
    era: '明清',
    period: '明朝',
    gregorianDate: '1368年 - 1644年',
    title: '大明王朝与郑和下西洋',
    summary: '朱元璋建立明朝，废除丞相制度；郑和下西洋展示航海实力。',
    region: '全国',
    evidence: '明十三陵、故宫（紫禁城）、明长城',
  },
  {
    id: 'evt-21-1',
    era: '明清',
    period: '后金',
    gregorianDate: '1616年 - 1636年',
    title: '努尔哈赤建立后金',
    summary: '努尔哈赤统一女真各部，建立后金政权，定都赫图阿拉（今辽宁新宾）。',
    region: '东北',
    evidence: '沈阳故宫早期建筑、赫图阿拉城遗址',
  },
  {
    id: 'evt-22',
    era: '明清',
    period: '清朝',
    gregorianDate: '1636年 - 1912年',
    title: '清朝统治与康乾盛世',
    summary: '皇太极改国号为清，1644年清军入关。奠定了现代中国的版图。1840年鸦片战争后，中国逐渐沦为半殖民地半封建社会。',
    region: '全国',
    evidence: '清东陵、避暑山庄、圆明园遗址',
  },
  {
    id: 'evt-23',
    era: '近现代',
    period: '中华民国',
    gregorianDate: '1912年 - 1949年',
    title: '辛亥革命与中华民国',
    summary: '辛亥革命推翻封建帝制，建立资产阶级民主共和国。处于半殖民地半封建社会时期。',
    region: '全国',
    evidence: '南京总统府、黄埔军校旧址',
  },
  {
    id: 'evt-24',
    era: '近现代',
    period: '中华人民共和国',
    gregorianDate: '1949年10月1日 - 至今',
    title: '新中国成立与社会主义建设',
    summary: '1949年成立，经历过渡时期(1949-1956)后，1956年正式进入社会主义社会。',
    region: '全国',
    evidence: '天安门广场人民英雄纪念碑',
  },
];

export const archaeologySites: ArchaeologySite[] = [
  {
    id: 'site-1',
    name: '周口店遗址',
    region: '华北',
    period: '旧石器时代',
    latitude: 39.68,
    longitude: 115.93,
    highlight: '古人类化石',
    significance: '人类演化与用火行为研究核心地点。',
    importance: '核心',
  },
  {
    id: 'site-2',
    name: '半坡遗址',
    region: '黄河中游',
    period: '新石器时代',
    latitude: 34.29,
    longitude: 108.99,
    highlight: '彩陶与聚落',
    significance: '揭示早期农业社会的居住与生产组织。',
    importance: '重要',
  },
  {
    id: 'site-3',
    name: '良渚古城',
    region: '长江下游',
    period: '新石器时代晚期',
    latitude: 30.38,
    longitude: 119.97,
    highlight: '水利系统',
    significance: '展示复杂社会治理能力与礼制体系。',
    importance: '核心',
  },
  {
    id: 'site-4',
    name: '二里头遗址',
    region: '中原',
    period: '青铜时代早期',
    latitude: 34.7,
    longitude: 112.62,
    highlight: '宫殿区',
    significance: '早期国家形成与都邑规划的重要证据。',
    importance: '核心',
  },
  {
    id: 'site-5',
    name: '殷墟遗址',
    region: '中原',
    period: '晚商',
    latitude: 36.13,
    longitude: 114.33,
    highlight: '甲骨文',
    significance: '文字、王权与祭祀系统研究关键样本。',
    importance: '核心',
  },
  {
    id: 'site-6',
    name: '三星堆遗址',
    region: '西南',
    period: '青铜时代',
    latitude: 31.01,
    longitude: 104.26,
    highlight: '青铜面具',
    significance: '多元区域文明交流与工艺创新的重要见证。',
    importance: '核心',
    culturalCircle: '西南文化圈',
  },
  {
    id: 'site-7',
    name: '贾湖遗址',
    region: '黄河中游',
    period: '新石器时代',
    latitude: 33.62,
    longitude: 113.68,
    highlight: '骨笛与原始文字',
    significance: '发现世界上最早的吹奏乐器和可能的原生文字符号。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
    relatedArtifacts: ['art-4'],
  },
  {
    id: 'site-8',
    name: '龙山文化遗址',
    region: '黄河中游',
    period: '新石器时代晚期',
    latitude: 36.73,
    longitude: 117.13,
    highlight: '黑陶技术',
    significance: '代表新石器时代晚期黄河流域的先进文明。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
  },
  {
    id: 'site-9',
    name: '红山文化遗址',
    region: '华北',
    period: '新石器时代',
    latitude: 41.97,
    longitude: 119.57,
    highlight: '玉猪龙',
    significance: '展现东北地区独特的玉器文明和祭祀文化。',
    importance: '重要',
    culturalCircle: '东北文化圈',
  },
  {
    id: 'site-10',
    name: '石峁遗址',
    region: '黄河中游',
    period: '新石器时代晚期',
    latitude: 38.55,
    longitude: 110.33,
    highlight: '大型石城',
    significance: '中国北方地区已发现规模最大的史前石城遗址。',
    importance: '核心',
    culturalCircle: '黄河文化圈',
  },
  {
    id: 'site-11',
    name: '马家窑文化遗址',
    region: '西北',
    period: '新石器时代',
    latitude: 35.32,
    longitude: 103.18,
    highlight: '彩陶艺术',
    significance: '黄土高原地区彩陶传统的代表，反映手工业分工与审美体系。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
    relatedArtifacts: ['art-1'],
  },
  {
    id: 'site-12',
    name: '大汶口文化遗址',
    region: '黄河下游',
    period: '新石器时代晚期',
    latitude: 36.2,
    longitude: 117.12,
    highlight: '墓葬分化',
    significance: '展示社会分层与礼仪制度演进，是龙山文化前段的重要基础。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
  },
  {
    id: 'site-13',
    name: '陶寺遗址',
    region: '中原',
    period: '新石器时代晚期',
    latitude: 35.87,
    longitude: 111.5,
    highlight: '观象台遗迹',
    significance: '体现早期都邑规划、礼制空间和天文观测实践。',
    importance: '核心',
    culturalCircle: '中原文化圈',
  },
  // ==================== 旧石器时代遗址 ====================
  {
    id: 'site-14',
    name: '元谋人遗址',
    region: '西南',
    period: '旧石器时代',
    latitude: 25.73,
    longitude: 101.88,
    highlight: '元谋人牙齿化石',
    significance: '中国南方最早的直立人证据，距今约170万年。',
    importance: '核心',
    culturalCircle: '西南文化圈',
    description: '1965年发现，出土两枚直立人牙齿化石，是中国境内发现的最早的古人类化石之一。',
  },
  {
    id: 'site-15',
    name: '蓝田人遗址',
    region: '黄河中游',
    period: '旧石器时代',
    latitude: 34.17,
    longitude: 109.32,
    highlight: '蓝田人头盖骨',
    significance: '距今约115-70万年的直立人化石，研究人类演化的重要材料。',
    importance: '核心',
    culturalCircle: '黄河文化圈',
    description: '1963-1964年发现，包括公主岭和陈家窝两个地点，出土了完整的头盖骨和下颌骨。',
  },
  {
    id: 'site-16',
    name: '巫山人遗址',
    region: '西南',
    period: '旧石器时代',
    latitude: 31.08,
    longitude: 109.63,
    highlight: '巫山人下颌骨',
    significance: '中国境内最早的古人类证据之一，距今约204-214万年。',
    importance: '核心',
    culturalCircle: '西南文化圈',
    description: '1985年发现于重庆巫山县龙骨坡，出土了距今约200万年的古人类化石。',
  },
  {
    id: 'site-17',
    name: '丁村遗址',
    region: '黄河中游',
    period: '旧石器时代',
    latitude: 35.88,
    longitude: 111.4,
    highlight: '丁村人牙齿与石器',
    significance: '早期智人文化特征研究的重要遗址，距今约20-10万年。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
    description: '1954年发现，出土了丁村人牙齿化石和大量石器，代表了旧石器时代中期的文化。',
  },
  {
    id: 'site-18',
    name: '山顶洞遗址',
    region: '华北',
    period: '旧石器时代',
    latitude: 39.68,
    longitude: 115.93,
    highlight: '晚期智人化石与装饰品',
    significance: '距今约3-2万年，展示了现代行为特征的出现。',
    importance: '核心',
    culturalCircle: '华北文化圈',
    description: '位于周口店北京人遗址顶部，出土了完整的人类化石、骨针、装饰品等。',
  },
  {
    id: 'site-19',
    name: '许昌人遗址',
    region: '中原',
    period: '旧石器时代',
    latitude: 34.02,
    longitude: 113.85,
    highlight: '许昌人头骨化石',
    significance: '现代人起源研究的重要发现，距今约12.5-10.5万年。',
    importance: '重要',
    culturalCircle: '中原文化圈',
    description: '2007年发现于河南许昌灵井遗址，出土了较完整的古人类头骨化石。',
  },
  {
    id: 'site-20',
    name: '泥河湾遗址群',
    region: '华北',
    period: '旧石器时代',
    latitude: 40.15,
    longitude: 114.68,
    highlight: '百万年人类活动序列',
    significance: '包含从200万年到1万年的连续文化堆积，是人类演化研究的宝库。',
    importance: '核心',
    culturalCircle: '华北文化圈',
    description: '位于河北阳原县，包含马圈沟、小长梁、东谷坨等多个遗址点。',
  },
  // ==================== 新石器时代早期遗址（农业起源） ====================
  {
    id: 'site-21',
    name: '玉蟾岩遗址',
    region: '长江中游',
    period: '旧新石器过渡',
    latitude: 25.52,
    longitude: 111.47,
    highlight: '世界最早栽培稻',
    significance: '发现世界上最早的人工栽培稻，距今约1.8-1.4万年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于湖南道县，出土了4粒炭化稻谷和早期陶器，是稻作农业起源的关键证据。',
  },
  {
    id: 'site-22',
    name: '仙人洞与吊桶环遗址',
    region: '长江中游',
    period: '旧新石器过渡',
    latitude: 28.92,
    longitude: 117.23,
    highlight: '稻作驯化证据',
    significance: '世界最早稻作农业起源地之一，距今约2.3-1.2万年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于江西万年县，通过植硅体分析发现了早期稻作驯化的证据。',
  },
  {
    id: 'site-23',
    name: '上山遗址',
    region: '长江下游',
    period: '新石器时代早期',
    latitude: 29.48,
    longitude: 119.85,
    highlight: '炭化稻米与环壕',
    significance: '证实长江下游早期稻作农业，距今约1.1-0.9万年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于浙江浦江，发现了大量炭化稻米和环壕聚落遗迹。',
  },
  {
    id: 'site-24',
    name: '磁山遗址',
    region: '黄河中游',
    period: '新石器时代',
    latitude: 36.72,
    longitude: 114.2,
    highlight: '大量炭化粟（小米）',
    significance: '粟作农业重要证据，发现约10万斤粟，距今约8000-7500年。',
    importance: '核心',
    culturalCircle: '黄河文化圈',
    description: '位于河北武安，发现了大量储粮窖穴和炭化粟，是粟作农业确立的证据。',
  },
  {
    id: 'site-25',
    name: '裴李岗遗址',
    region: '中原',
    period: '新石器时代',
    latitude: 34.53,
    longitude: 113.85,
    highlight: '早期农业与石器',
    significance: '中原地区早期农业文化代表，距今约8500-7000年。',
    importance: '重要',
    culturalCircle: '中原文化圈',
    description: '位于河南新郑，出土了农业工具、陶器和粟黍遗存。',
  },
  // ==================== 新石器时代重要遗址 ====================
  {
    id: 'site-26',
    name: '河姆渡遗址',
    region: '长江下游',
    period: '新石器时代',
    latitude: 29.95,
    longitude: 121.33,
    highlight: '干栏建筑与稻作',
    significance: '成熟稻作农业与干栏式建筑代表，距今约7000-5300年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于浙江余姚，发现了大量稻谷、干栏式建筑和漆器。',
  },
  {
    id: 'site-27',
    name: '兴隆洼遗址',
    region: '东北',
    period: '新石器时代',
    latitude: 42.3,
    longitude: 119.85,
    highlight: '最早玉器与环壕',
    significance: '中国最早玉器出土地，距今约8200-7400年。',
    importance: '核心',
    culturalCircle: '东北文化圈',
    description: '位于内蒙古敖汉旗，发现了环壕聚落和中国最早的玉器。',
  },
  {
    id: 'site-28',
    name: '牛河梁遗址',
    region: '东北',
    period: '新石器时代',
    latitude: 41.3,
    longitude: 119.42,
    highlight: '女神庙与积石冢',
    significance: '红山文化祭祀中心，距今约6500-5000年。',
    importance: '核心',
    culturalCircle: '东北文化圈',
    description: '位于辽宁建平，发现了女神庙、积石冢和大量玉器，包括玉猪龙。',
  },
  {
    id: 'site-29',
    name: '彭头山遗址',
    region: '长江中游',
    period: '新石器时代',
    latitude: 29.38,
    longitude: 111.78,
    highlight: '早期稻作与绳纹陶',
    significance: '彭头山文化命名地，距今约9000-7800年。',
    importance: '重要',
    culturalCircle: '长江文化圈',
    description: '位于湖南澧县，发现了大量炭化稻和早期陶器。',
  },
  {
    id: 'site-30',
    name: '城头山遗址',
    region: '长江中游',
    period: '新石器时代',
    latitude: 29.68,
    longitude: 111.63,
    highlight: '中国最早城址',
    significance: '中国已发现的最早城址，距今约6500年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于湖南澧县，发现了城墙、护城河和稻田遗迹。',
  },
  {
    id: 'site-31',
    name: '大地湾遗址',
    region: '西北',
    period: '新石器时代',
    latitude: 35.03,
    longitude: 105.93,
    highlight: '大型建筑与彩陶',
    significance: '西北地区新石器时代重要遗址，距今约7800-4800年。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
    description: '位于甘肃秦安，发现了大型宫殿式建筑和彩陶。',
  },
  {
    id: 'site-32',
    name: '跨湖桥遗址',
    region: '长江下游',
    period: '新石器时代',
    latitude: 30.18,
    longitude: 120.25,
    highlight: '独木舟与早期稻作',
    significance: '发现世界最早独木舟，距今约8000-7000年。',
    importance: '重要',
    culturalCircle: '长江文化圈',
    description: '位于浙江杭州萧山，发现了独木舟、稻米和橡子等植物遗存。',
  },
  // ==================== 青铜时代与早期国家 ====================
  {
    id: 'site-33',
    name: '金沙遗址',
    region: '西南',
    period: '青铜时代',
    latitude: 30.68,
    longitude: 104.02,
    highlight: '金面具与象牙',
    significance: '古蜀文明延续，三星堆之后的成都平原中心，距今约3200-2600年。',
    importance: '核心',
    culturalCircle: '西南文化圈',
    description: '位于四川成都，出土了金面具、金箔、象牙和玉器等珍贵文物。',
  },
  {
    id: 'site-34',
    name: '周原遗址',
    region: '黄河中游',
    period: '青铜时代',
    latitude: 34.45,
    longitude: 107.62,
    highlight: '青铜器窖藏与甲骨文',
    significance: '周人发祥地，出土大量青铜器和甲骨文，距今约3200-2700年。',
    importance: '核心',
    culturalCircle: '黄河文化圈',
    description: '位于陕西扶风、岐山一带，是周文化的核心区域。',
  },
  {
    id: 'site-35',
    name: '丰镐遗址',
    region: '黄河中游',
    period: '青铜时代',
    latitude: 34.23,
    longitude: 108.83,
    highlight: '西周都城',
    significance: '西周王朝都城遗址，距今约3000-2700年。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
    description: '位于陕西西安，是西周时期的政治中心。',
  },
  {
    id: 'site-36',
    name: '琉璃河遗址',
    region: '华北',
    period: '青铜时代',
    latitude: 39.58,
    longitude: 116.03,
    highlight: '燕国都城与墓地',
    significance: '西周燕国都城遗址，距今约3000年。',
    importance: '重要',
    culturalCircle: '华北文化圈',
    description: '位于北京房山，发现了城址和燕国墓地。',
  },
  {
    id: 'site-37',
    name: '偃师商城遗址',
    region: '中原',
    period: '青铜时代',
    latitude: 34.73,
    longitude: 112.78,
    highlight: '商代早期都城',
    significance: '商代早期都城遗址，距今约3500年。',
    importance: '重要',
    culturalCircle: '中原文化圈',
    description: '位于河南偃师，是商代早期的都城遗址。',
  },
  {
    id: 'site-38',
    name: '郑州商城遗址',
    region: '中原',
    period: '青铜时代',
    latitude: 34.75,
    longitude: 113.67,
    highlight: '商代都城与青铜器',
    significance: '商代早期都城，发现大型宫殿和青铜器窖藏，距今约3500年。',
    importance: '核心',
    culturalCircle: '中原文化圈',
    description: '位于河南郑州，发现了城墙、宫殿区和青铜器窖藏。',
  },
  // ==================== 秦汉及以后重要遗址 ====================
  {
    id: 'site-39',
    name: '秦始皇陵',
    region: '黄河中游',
    period: '秦代',
    latitude: 34.38,
    longitude: 109.28,
    highlight: '兵马俑与帝陵',
    significance: '中国第一位皇帝陵墓，世界文化遗产，距今约2200年。',
    importance: '核心',
    culturalCircle: '黄河文化圈',
    description: '位于陕西临潼，发现了兵马俑坑、铜车马等珍贵文物。',
  },
  {
    id: 'site-40',
    name: '马王堆汉墓',
    region: '长江中游',
    period: '汉代',
    latitude: 28.2,
    longitude: 113.08,
    highlight: '辛追夫人与帛书',
    significance: '保存完好的汉代墓葬，出土女尸和大量文物，距今约2100年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于湖南长沙，出土了保存完好的女尸、帛书和漆器。',
  },
  {
    id: 'site-41',
    name: '海昏侯墓',
    region: '长江中游',
    period: '汉代',
    latitude: 28.55,
    longitude: 115.82,
    highlight: '大量金器与简牍',
    significance: '汉代诸侯王墓，出土大量金器和简牍，距今约2000年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于江西南昌，出土了金饼、马蹄金、简牍等珍贵文物。',
  },
  {
    id: 'site-42',
    name: '曾侯乙墓',
    region: '长江中游',
    period: '战国',
    latitude: 31.72,
    longitude: 113.38,
    highlight: '编钟与青铜器',
    significance: '出土世界最大青铜编钟，距今约2400年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于湖北随州，出土了曾侯乙编钟、青铜器和漆器。',
  },
  // ==================== 其他重要遗址 ====================
  {
    id: 'site-43',
    name: '齐家坪遗址',
    region: '西北',
    period: '新石器时代晚期',
    latitude: 35.68,
    longitude: 104.37,
    highlight: '早期青铜器',
    significance: '齐家文化命名地，中国早期青铜器出土地，距今约4200-3800年。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
    description: '位于甘肃广河，发现了早期青铜器和玉器。',
  },
  {
    id: 'site-44',
    name: '石家河遗址',
    region: '长江中游',
    period: '新石器时代晚期',
    latitude: 30.77,
    longitude: 113.1,
    highlight: '大型城址与玉器',
    significance: '长江中游最大史前城址群，距今约4600-4000年。',
    importance: '核心',
    culturalCircle: '长江文化圈',
    description: '位于湖北天门，发现了大型城址和玉器。',
  },
  {
    id: 'site-45',
    name: '宝墩遗址',
    region: '西南',
    period: '新石器时代晚期',
    latitude: 30.58,
    longitude: 103.82,
    highlight: '成都平原最早城址',
    significance: '成都平原最早的古城群，距今约4800-4000年。',
    importance: '重要',
    culturalCircle: '西南文化圈',
    description: '位于四川新津，是古蜀文明的早期代表。',
  },
  {
    id: 'site-46',
    name: '屈家岭遗址',
    region: '长江中游',
    period: '新石器时代',
    latitude: 31.03,
    longitude: 112.88,
    highlight: '蛋壳彩陶',
    significance: '屈家岭文化命名地，距今约5300-4600年。',
    importance: '重要',
    culturalCircle: '长江文化圈',
    description: '位于湖北京山，以蛋壳彩陶闻名。',
  },
  {
    id: 'site-47',
    name: '庙底沟遗址',
    region: '中原',
    period: '新石器时代',
    latitude: 34.78,
    longitude: 111.17,
    highlight: '仰韶文化代表',
    significance: '仰韶文化庙底沟类型命名地，距今约6000-5000年。',
    importance: '重要',
    culturalCircle: '中原文化圈',
    description: '位于河南三门峡，是仰韶文化的重要代表。',
  },
  {
    id: 'site-48',
    name: '姜寨遗址',
    region: '黄河中游',
    period: '新石器时代',
    latitude: 34.42,
    longitude: 109.25,
    highlight: '完整聚落布局',
    significance: '保存完整的仰韶文化聚落，距今约6700-6000年。',
    importance: '重要',
    culturalCircle: '黄河文化圈',
    description: '位于陕西临潼，发现了完整的聚落布局和铜片。',
  },
  {
    id: 'site-49',
    name: '西阴村遗址',
    region: '中原',
    period: '新石器时代',
    latitude: 35.35,
    longitude: 111.35,
    highlight: '蚕茧遗迹',
    significance: '发现史前蚕茧，丝绸起源证据，距今约5500年。',
    importance: '重要',
    culturalCircle: '中原文化圈',
    description: '位于山西夏县，发现了史前蚕茧遗迹。',
  },
  {
    id: 'site-50',
    name: '青台遗址',
    region: '中原',
    period: '新石器时代',
    latitude: 34.85,
    longitude: 113.38,
    highlight: '丝绸残片',
    significance: '发现世界最早丝绸残片，距今约5500年。',
    importance: '重要',
    culturalCircle: '中原文化圈',
    description: '位于河南荥阳，出土了丝绸残片和瓮棺葬。',
  },
];

export const culturalCircles: CulturalCircle[] = [
  {
    id: 'circle-north',
    name: '华北文化圈',
    color: 'rgba(59, 130, 246, 0.15)',
    region: '华北',
    center: [39.5, 116.0],
    radius: 350,
    sites: ['site-1', 'site-9', 'site-18', 'site-20', 'site-36'],
  },
  {
    id: 'circle-yellow',
    name: '黄河文化圈',
    color: 'rgba(245, 158, 11, 0.15)',
    region: '黄河中游',
    center: [34.5, 111.0],
    radius: 450,
    sites: ['site-2', 'site-7', 'site-8', 'site-10', 'site-11', 'site-12', 'site-15', 'site-17', 'site-24', 'site-31', 'site-34', 'site-35', 'site-43', 'site-48'],
  },
  {
    id: 'circle-yangtze',
    name: '长江文化圈',
    color: 'rgba(16, 185, 129, 0.15)',
    region: '长江流域',
    center: [30.5, 114.0],
    radius: 500,
    sites: ['site-3', 'site-21', 'site-22', 'site-23', 'site-26', 'site-29', 'site-30', 'site-32', 'site-40', 'site-41', 'site-42', 'site-44', 'site-46'],
  },
  {
    id: 'circle-central',
    name: '中原文化圈',
    color: 'rgba(139, 92, 246, 0.15)',
    region: '中原',
    center: [34.8, 113.5],
    radius: 300,
    sites: ['site-4', 'site-5', 'site-13', 'site-19', 'site-25', 'site-37', 'site-38', 'site-47', 'site-49', 'site-50'],
  },
  {
    id: 'circle-southwest',
    name: '西南文化圈',
    color: 'rgba(236, 72, 153, 0.15)',
    region: '西南',
    center: [30.5, 104.0],
    radius: 350,
    sites: ['site-6', 'site-14', 'site-16', 'site-33', 'site-45'],
  },
  {
    id: 'circle-northeast',
    name: '东北文化圈',
    color: 'rgba(234, 88, 12, 0.15)',
    region: '东北',
    center: [41.5, 119.5],
    radius: 300,
    sites: ['site-27', 'site-28'],
  },
];

export const siteConnections: SiteConnection[] = [
  // 黄河文化圈连线
  { from: 'site-2', to: 'site-7', type: '文化圈', color: 'rgba(245, 158, 11, 0.6)', weight: 2 },
  { from: 'site-2', to: 'site-8', type: '文化圈', color: 'rgba(245, 158, 11, 0.6)', weight: 2 },
  { from: 'site-7', to: 'site-8', type: '文化圈', color: 'rgba(245, 158, 11, 0.6)', weight: 2 },
  { from: 'site-8', to: 'site-10', type: '文化圈', color: 'rgba(245, 158, 11, 0.6)', weight: 2 },
  { from: 'site-8', to: 'site-12', type: '文化圈', color: 'rgba(245, 158, 11, 0.6)', weight: 2 },
  { from: 'site-7', to: 'site-11', type: '文化圈', color: 'rgba(245, 158, 11, 0.6)', weight: 2 },
  { from: 'site-10', to: 'site-11', type: '文化圈', color: 'rgba(245, 158, 11, 0.6)', weight: 2 },
  // 中原文化圈连线
  { from: 'site-4', to: 'site-5', type: '文化圈', color: 'rgba(139, 92, 246, 0.6)', weight: 2 },
  { from: 'site-4', to: 'site-13', type: '文化圈', color: 'rgba(139, 92, 246, 0.6)', weight: 2 },
  { from: 'site-5', to: 'site-13', type: '文化圈', color: 'rgba(139, 92, 246, 0.6)', weight: 2 },
  // 新石器时代连线
  { from: 'site-2', to: 'site-3', type: '时期', color: 'rgba(249, 115, 22, 0.6)', weight: 3 },
  { from: 'site-2', to: 'site-7', type: '时期', color: 'rgba(249, 115, 22, 0.6)', weight: 3 },
  { from: 'site-3', to: 'site-8', type: '时期', color: 'rgba(249, 115, 22, 0.6)', weight: 3 },
  { from: 'site-3', to: 'site-10', type: '时期', color: 'rgba(249, 115, 22, 0.6)', weight: 3 },
  { from: 'site-8', to: 'site-12', type: '时期', color: 'rgba(249, 115, 22, 0.6)', weight: 3 },
  { from: 'site-12', to: 'site-13', type: '时期', color: 'rgba(249, 115, 22, 0.6)', weight: 3 },
  { from: 'site-7', to: 'site-11', type: '时期', color: 'rgba(249, 115, 22, 0.6)', weight: 3 },
  // 青铜时代连线
  { from: 'site-4', to: 'site-5', type: '时期', color: 'rgba(139, 92, 246, 0.6)', weight: 3 },
  { from: 'site-4', to: 'site-6', type: '时期', color: 'rgba(139, 92, 246, 0.6)', weight: 3 },
  { from: 'site-5', to: 'site-6', type: '时期', color: 'rgba(139, 92, 246, 0.6)', weight: 3 },
];

export const artifacts: Artifact[] = [
  {
    id: 'art-1',
    name: '人面鱼纹彩陶盆',
    period: '仰韶文化',
    category: '陶器',
    material: '陶',
    site: '半坡遗址',
    detail: '反映图像表达与仪式语义，是早期精神文化的重要线索。',
  },
  {
    id: 'art-2',
    name: '玉琮',
    period: '良渚文化',
    category: '玉器',
    material: '透闪石',
    site: '良渚古城',
    detail: '体现等级秩序与礼仪规范，常见于高等级墓葬。',
  },
  {
    id: 'art-3',
    name: '司母戊鼎',
    period: '商代',
    category: '青铜器',
    material: '青铜',
    site: '殷墟遗址',
    detail: '大型青铜铸造技术与王权礼制的代表性器物。',
  },
  {
    id: 'art-4',
    name: '骨笛',
    period: '新石器时代',
    category: '骨器',
    material: '鹤骨',
    site: '贾湖遗址',
    detail: '可演奏音阶显示早期音乐系统与认知能力发展。',
  },
  {
    id: 'art-5',
    name: '青铜神树残件',
    period: '三星堆文化',
    category: '礼器',
    material: '青铜',
    site: '三星堆遗址',
    detail: '体现区域神话体系与祭祀空间想象。',
  },
];

export const debates: Debate[] = [
  {
    id: 'debate-1',
    title: '夏王朝考古对应关系',
    topic: '年代学',
    mainstream: '二里头文化与早期国家形态存在高度对应，但需保持术语审慎。',
    alternative: '二里头可视作区域性强权中心，未必直接等同文献中的夏王朝。',
    evidenceLevel: '中',
  },
  {
    id: 'debate-2',
    title: '青铜技术来源路径',
    topic: '技术起源',
    mainstream: '本地技术演进为主，并在交流中吸收周边技术要素。',
    alternative: '关键冶金工艺可能由跨区域网络快速传播并重组。',
    evidenceLevel: '探索中',
  },
  {
    id: 'debate-3',
    title: '良渚社会形态判定',
    topic: '社会形态',
    mainstream: '具备复杂分层和公共工程，接近文明门槛或已进入文明阶段。',
    alternative: '应避免单一路径模型，良渚可能是独特区域复杂社会。',
    evidenceLevel: '高',
  },
  {
    id: 'debate-4',
    title: '欧亚文化因素交流强度',
    topic: '文化传播',
    mainstream: '交流存在但不改变中原及区域文明自主演进主轴。',
    alternative: '交流在技术与观念上可能更具结构性影响。',
    evidenceLevel: '中',
  },
];

export const originNarrative = [
  {
    title: '环境适应',
    description: '从气候波动到生态位选择，早期人群通过采集、狩猎与火使用提升生存韧性。',
  },
  {
    title: '技术积累',
    description: '石器标准化、陶器烧制、农业工具改进推动生产效率与协作方式改变。',
  },
  {
    title: '社会组织',
    description: '聚落扩展、公共工程和礼仪空间形成，促成社会分工与治理结构出现。',
  },
  {
    title: '符号系统',
    description: '纹饰、祭祀和文字实践逐步建立跨代记忆与共同认同。',
  },
];

export const themes: Theme[] = [
  {
    id: 'theme-1',
    title: '仰韶文化：农业与聚落协作',
    era: '早期文明',
    region: '黄河中游',
    summary: '关注彩陶、房址与墓地结构，理解定居社会的组织逻辑。',
    focus: '聚落结构、生产协作、精神表达',
  },
  {
    id: 'theme-2',
    title: '良渚文明：工程与礼制秩序',
    era: '早期文明',
    region: '长江下游',
    summary: '结合水利系统和玉礼器谱系，观察复杂社会治理机制。',
    focus: '大型工程、等级秩序、仪式体系',
  },
  {
    id: 'theme-3',
    title: '殷墟：文字与王权体系',
    era: '夏商周',
    region: '中原',
    summary: '通过甲骨文与青铜礼器，研究国家治理与宗教实践关系。',
    focus: '甲骨卜辞、王权结构、礼制实践',
  },
  {
    id: 'theme-4',
    title: '三星堆：区域文明与交流网络',
    era: '夏商周',
    region: '西南',
    summary: '聚焦独特器物组合与祭祀坑现象，讨论多元文明并行发展。',
    focus: '区域创新、跨域交流、神话体系',
  },
];
